#define cesium_main main
typedef enum {false = 0, true = 1} bool;
#include<stdio.h>
;
#include<stdlib.h>
;
#include<string.h>
;
unsigned long long int getstrlen(const unsigned char* str ) {;
unsigned long long int r = 0;
while (str[r] != 0) {;
r++;
};
r++;
return r;
};
void printbool(const bool v ) {;
if (v == true) {;
printf("true");
};
if (v != true) {;
printf("false");
};
};
unsigned long long int append(const unsigned char* fn ,const unsigned char* block ,const unsigned long long int size ) {;
if (block == NULL) {;
return NULL;
};
const unsigned long long int* f = fopen(fn, "a");
if (f == NULL) {;
return NULL;
};
fwrite(block, 1, size, f);
fclose(f);
return block;
};
bool u8isin(const unsigned char* keys ,const unsigned long long int ks ,const unsigned char part ) {;
if (ks < 1) {;
return false;
};
unsigned long long int p = 0;
while (p < ks) {;
if (keys[p] == part) {;
return true;
};
p++;
};
return false;
};
unsigned long long int fsize(const unsigned char* fn ) {;
const unsigned long long int* f = ((unsigned long long int)fopen(fn, "rb") );
fseek(f, 0, SEEK_END);
const unsigned long long int size = ftell(f);
fclose(f);
return size;
};
unsigned char* fget(const unsigned char* fn ) {;
if (fn == NULL) {;
return NULL;
};
const unsigned long long int* f = ((unsigned long long int)fopen(fn, "rb") );
if (f == NULL) {;
return NULL;
};
const unsigned long long int size = fsize(fn);
unsigned char* block = malloc(size+1);
if (block == NULL) {;
return NULL;
};
fread(block, 1, size, f);
fclose(f);
block[size+1] = 0;
return block;
};
#include <unistd.h>
;
unsigned char* fin = NULL;
unsigned char* foutmid = NULL;
unsigned char* gcc_args = NULL;
unsigned char* foutc = NULL;
unsigned long long int clayer = 0;
bool cflag = true;
unsigned char* fout = NULL;
int leave() {;
if (fin != NULL) {;
free(fin);
};
if (foutc != NULL) {;
free(foutc);
};
if (foutmid != NULL) {;
free(foutmid);
};
if (gcc_args != NULL) {;
free(gcc_args);
};
printf("\n");
return 0;
};
bool startswith(const unsigned char* s1 ,const unsigned char* s2 ) {;
unsigned long long int p = -1;
while (true) {;
p++;
if (s2[p] == 0) {;
break;
};
if (s2[p] == s1[p]) {;
continue;
};
if (s1[p] == 0) {;
return false;
};
return false;
};
if (u8isin("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_", getstrlen("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_") - 1, s1[p]) == false) {;
return true;
};
return false;
};
unsigned long long int getlinelen(const unsigned char* str ) {;
unsigned long long int r = 0;
while ((str[r] != '\n') && (str[r] != 0) && (str[r] != ';')) {;
r++;
};
r++;
return r;
};
unsigned char* do_block(const unsigned char* block ) {;
};
unsigned long long int parse_layer = 0;
unsigned char* parse_line(const unsigned char* in ) {;
unsigned long long int offset = 0;
while ((in[offset] == ' ') || (in[offset] == '\t')) {;
offset++;
};
const unsigned char* line = in + offset;
if (startswith(line, "import")) {;
unsigned long long int p = 6;
while (true) {;
if ((line[p] == ' ') || (line[p] == '\t')) {;
p++;
continue;
};
break;
};
return line + p;
};
if (startswith(line, "break")) {;
parse_layer++;
const unsigned char* lay = malloc(parse_layer + 2);
strcpy(lay, "");
unsigned long long int p = 0;
while (p != parse_layer) {;
strcat(lay, ":");
p++;
};
strcat(lay, ">");
append(foutmid, lay,(unsigned long long int) (getstrlen(lay) - 1) );
append(foutmid, "break\n",(unsigned long long int) (getstrlen("break\n") - 1) );
append(foutmid, lay,(unsigned long long int) (getstrlen(lay) - 1) );
append(foutmid, "ENDSTATEMENT\n",(unsigned long long int) (getstrlen("ENDSTATEMENT\n") - 1) );
parse_layer--;
return NULL;
};
if (startswith(line, "continue")) {;
parse_layer++;
const unsigned char* lay = malloc(parse_layer + 2);
strcpy(lay, "");
unsigned long long int p = 0;
while (p != parse_layer) {;
p++;
strcat(lay, ":");
};
strcat(lay, ">");
append(foutmid, lay,(unsigned long long int) (getstrlen(lay) - 1) );
append(foutmid, "continue\n",(unsigned long long int) (getstrlen("continue\n") - 1) );
append(foutmid, lay,(unsigned long long int) (getstrlen(lay) - 1) );
append(foutmid, "ENDSTATEMENT\n",(unsigned long long int) (getstrlen("ENDSTATEMENT\n") - 1) );
parse_layer--;
return NULL;
};
return NULL;
};
unsigned char* gimpf(const unsigned char* fn ,unsigned char* block ) {;
if (startswith(fn, "/") || startswith(fn, ".") || startswith(fn, "~")) {;
return fn;
};
unsigned char b1[2048] ;
readlink("/proc/self/exe", b1, 2048-270);
const unsigned char* *last_slash = strrchr(b1, '/');;
*last_slash = 0;
strcpy(block, b1);
strcat(block, "/lib/");
strcat(block, fn);
return block;
};
void parse() {;
unsigned long long int e = getstrlen(fin);
unsigned long long int p = 0;
while (p <= e) {;
const unsigned long long int llen = getlinelen((fin+p));
unsigned char* l = malloc(llen);
unsigned long long int i = 0;
while (i != (llen - 1)) {;
l[i] = (fin+p)[i];
i++;
};
l[i] = 0;
unsigned long long int offset = 0;
while ((l[offset] == ' ') || (l[offset] == '\t')) {;
offset++;
};
const unsigned char* line = l + offset;
if (startswith(line, "c")) {;
cflag = true;
unsigned long long int i = 0;
while (line[i] != 0) {;
if (line[i] == 0x7b) {;
clayer++;
};
if (line[i] == 0x7d) {;
clayer--;
};
i++;
};
free(l);
p += llen;
continue;
};
if (parse_line(l) != NULL) {;
char path[2048];;
const unsigned char* fimp = fget(gimpf(parse_line(l), path));
if (fimp == NULL) {;
printf("ERROR: Could not read: %s\n", fimp);
return leave();
};
const unsigned long long int fimps = getstrlen(fimp);
unsigned char* block = malloc(e + fimps + 1);
unsigned long long int p1 = 0;
unsigned long long int p2 = 0;
while (p2 != p) {;
block[p1++] = fin[p2++];
};
p2 = 0;
while (p2 != fimps-1) {;
block[p1++] = fimp[p2++];
};
p2 = p + llen;
while (p2 != e+1) {;
block[p1++] = fin[p2++];
};
free(fimp);
free(fin);
fin = block;
e = getstrlen(fin);
};
free(l);
p += llen;
};
return;
};
int main(const int argc ,const unsigned char** args ) {;
unsigned long long int i = 2;
unsigned long long int out_args_len = 1;
while (i != argc) {;
out_args_len +=(unsigned long long int) (getstrlen(args[i])) ;
i++;
};
gcc_args = malloc(out_args_len);
gcc_args[0] = 0;
strcat;
i = 2;
while (i != argc) {;
strcat(gcc_args, args[i]);
strcat(gcc_args, " ");
i++;
};
foutmid = malloc((unsigned long long int)(getstrlen(args[1]) + getstrlen(".midpoint") - 1) );
strcpy(foutmid, args[1]);
strcat(foutmid, ".midpoint");
const unsigned long long int* f = fopen(foutmid, "w");
if (f == NULL) {;
printf("ERROR: Could not open: %s\n", foutmid);
return leave();
};
fclose(f);
foutc = malloc((unsigned long long int)(getstrlen(args[1]) + getstrlen(".c") - 1) );
strcpy(foutc, args[1]);
strcat(foutc, ".c");
f = fopen(foutc, "w");
if (f == NULL) {;
printf("ERROR: Could not open: %s\n", foutc);
return leave();
};
fclose(f);
fin = fget(args[1]);
if (fin == NULL) {;
printf("ERROR: Could not read: %s\n", args[1]);
return leave();
};
parse();
unsigned char* cmd = malloc(getstrlen(gcc_args) + getstrlen(foutc) + getstrlen("gcc "));
strcpy(cmd, "gcc ");
strcat(cmd, foutc);
strcat(cmd, " ");
strcat(cmd, gcc_args);
printf("\nCompile with: %s\n\n", cmd);
free(cmd);
return leave();
};
